services:
  app:
    image: ghcr.io/axsddlr/telerss:latest
    ports:
      - "3000:3000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DATABASE_URL=file:/data/db.sqlite
      - SECRETS_FILE_PATH=/data/secrets.json
      - NODE_ENV=production
    volumes:
      - sqlite_data:/data
    restart: unless-stopped

volumes:
  sqlite_data:
